packages:
  - e2e
  - packages/*

catalogs:
  lint:
    eslint: ^9.0.0
  project:
    presetter: ^8.3.0
    presetter-preset-monorepo: ^8.3.0
    presetter-preset-react: ^8.3.0
  test:
    '@vitest/coverage-v8': ^4.0.0
    undici: ^7.0.0
    vitest: ^4.0.0
  utility:
    ajv: ^8.0.0

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
